workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      vars:
        # Add any environment variables here if needed
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Podfile.lock
        script: |
          cd ios
          if [ -f Podfile.lock ]; then
            echo "Deleting Podfile.lock"
            rm Podfile.lock
          fi
          cd ..
      - name: Install Pods
        script: |
          cd ios
          pod install --repo-update
          cd ..
      - name: Build Debug iOS App
        script: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Debug \
            -sdk iphoneos \
            clean build
    artifacts:
      - ios/Runner/Build/Products/Debug-iphoneos/*.app
