workflows:
  ios-debug:
    name: iOS Debug Build
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Clean Podfile.lock
        script: |
          if [ -f Podfile.lock ]; then
            echo "Deleting Podfile.lock"
            rm Podfile.lock
          fi
      - name: Install Pods
        script: |
          if [ -f Podfile ]; then
            pod install --repo-update
          fi
      - name: Build Debug iOS App
        script: |
          xcodebuild \
            -scheme FinorimaMobileApp \
            -configuration Debug \
            clean build
    artifacts:
      - build/Debug-iphoneos/*.app
